---
#TODO: test on both RHEL, Ubuntu
language: python
python: "2.7"

#before_install:
#  # Make sure everything's up to date.
#  - sudo apt-get update -qq

install:
  #- pip install ansible
  #- "printf '[defaults]\\nroles_path = ../' > ansible.cfg"
  - pip install ansible-lint

#before_script:
#  - echo localhost > inventory
#  - ansible-galaxy install --role-file requirements.yml

script:
  ### Check syntax
  #- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  ### Check Lint
  - ansible-lint -v $(find tests -name *yml) -x ANSIBLE0010
  ### Test run
  #- "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
  ### Test idempotence
  #- >
  #  ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  #  | grep -q 'changed=0.*failed=0'
  #  && (echo 'Idempotence test: pass' && exit 0)
  #  || (echo 'Idempotence test: fail' && exit 1)
